### ISSUE TITLE
Failure when creating a container using the template debian-wheezy: Unknown Option »--rootfs=/var/lib/lxc/omv-dev/rootfs«

### ISSUE THREAD

**Issue by cmonty14** [simonvanderveldt/lxc-debian-wheezy-template#16]
Hello!

I'm using the script from master branch, but I cannot create a container.
The script fails with this error:
sudo lxc-create -n omv-dev -t debian-wheezy
getopt: Unbekannte Option »--rootfs=/var/lib/lxc/omv-dev/rootfs«
lxc-debian-wheezy -h|--help -p|--path=<path> --clean
lxc_container: container creation template for omv-dev failed
lxc_container: Error creating container omv-dev

Could you please advise how to resolve this issue?

I have installed LXC release 1.0.6-6 running in system LMDE (Linux Mint Debian Edition) based on Debian 7.

THX

**Comment by simonvanderveldt** [comment]
Thanks for reporting. I'll try to get a LMDE box up this week and check what's going on.
Maybe you can give the `newtemplate` branch a try in the meantime, it contains some fixes to the original template.

**Comment by cmonty14** [comment]
The error remains independent which branch is used.

**Comment by simonvanderveldt** [comment]
OK, thanks for checking that out. I've got an LMDE box running, will try and see if I can reproduce the issue this week.

**Comment by hungpr0** [comment]
Hi,

I also have that issue on debian 7 with lxc 1.0.6-6+deb8u6. Can you have a check? I couldn't find --rootfs in the template.

**Comment by simonvanderveldt** [comment]
@Diamond2 Thanks for getting in touch. Unfortunately I don't use either LXC nor Debian any more and haven't done so for a couple of years. To be honest I don't really have the time to invest into figuring out these issue. I guess that means this repo should be seen as abandoned, I'll mark it as such.

Since this template was made for LXC 0.8.0 I guess some incompatible change was introduced somewhere between 0.8.0 and your version 1.0.6. I did a quick check on the [changelog](https://linuxcontainers.org/lxc/news/) and grep on the [sources](https://github.com/lxc/lxc) but couldn't really find anything that stuck out. Maybe you'll be able to find it yourself?

Also, is the template included in Debian still broken? That would be very sad :(
