### ISSUE TITLE
DHCPDISCOVER even when static IP is set

### ISSUE THREAD

**Issue by Napsty** [simonvanderveldt/lxc-debian-wheezy-template#2]
Hi Simon, 
First of all thank you a lot for doing something to solve that issue. We're using Debian stable (don't want to run testing for a production environment) and therefore have the lxc template issue on Wheezy. 

The template of Rob seems to work so far (comparing to the one coming from Debian), however I have a minor bug to report. 

When I start a container, it always seems to search an ip address through DHCPDISCOVER. However, I set static IPv4 addresses in the config file. After a while DHCPDISCOVER gives up and then the static IP is set. 

```
# lxc-start -n lxcmachine
INIT: version 2.88 booting
[info] Using makefile-style concurrent boot in runlevel S.
[ ok ] Activating swap...done.
[warn] Creating compatibility symlink from /etc/mtab to /proc/mounts. ... (warning).
[ ok ] Cleaning up temporary files... /tmp.
[warn] Mount point '/dev/console' does not exist. Skipping mount. ... (warning).
[warn] Mount point '/dev/tty1' does not exist. Skipping mount. ... (warning).
[warn] Mount point '/dev/tty2' does not exist. Skipping mount. ... (warning).
[warn] Mount point '/dev/tty3' does not exist. Skipping mount. ... (warning).
[warn] Mount point '/dev/tty4' does not exist. Skipping mount. ... (warning).
[warn] Mount point '/dev/ptmx' does not exist. Skipping mount. ... (warning).
[ ok ] Activating lvm and md swap...done.
[....] Checking file systems...fsck from util-linux 2.20.1
done.
[ ok ] Mounting local filesystems...done.
/etc/init.d/mountall.sh: 59: kill: Illegal number: 3 1
[ ok ] Activating swapfile swap...done.
[ ok ] Cleaning up temporary files....
[ ok ] Setting kernel variables ...done.
[....] Configuring network interfaces...Internet Systems Consortium DHCP Client
Copyright 2004-2011 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/00:1e:cf:48:bd:1d
Sending on   LPF/eth0/00:1e:cf:48:bd:1d
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 4
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 13
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14
No DHCPOFFERS received.
No working leases in persistent database - sleeping.
done.
[ ok ] Cleaning up temporary files....
INIT: Entering runlevel: 3
[info] Using makefile-style concurrent boot in runlevel 3.
[ ok ] Starting OpenBSD Secure Shell server: sshd.

Debian GNU/Linux 7.0 anothertest console

lxcmachine login:
```

Why is that? The container should start up with the IPv4 address given in the config file.

**Comment by Napsty** [comment]
Just found this information in the template file....

```
    # configure the network using the dhcp
    cat <<EOF > $rootfs/etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
EOF
```

Just tested it and this part is indeed responsible for the DHCPDISCOVER.

**Comment by simonvanderveldt** [comment]
No problem :) I really hope us users can get something together that works properly.

Regarding DHCP, as you already found in the template the cat to /etc/network/interfaces always contains an eth0 with DHCP, which is why you're seeing a DHCPDISCOVER when starting your container.

I guess the cleanest way of fixing this would be:
- Check if an IP address has been set through a config file (lxc.network.ipv4 = #.#.#.#)
  - If not: do what's in the template now, i.e.:
    - add container network config for ipv4 and DHCP
    - cat to /etc/network/interfaces for eth0 with ipv4 and DHCP
  - If it is and lxc.network.ipv4 is 0.0.0.0, then cat what's in the template now to /etc/network/interfaces
  - If it is and lxc.network.ipv4 is something else than 0.0.0.0, then cat a basic static config to /etc/network/interfaces

The only issue I see with this is that I think it's impossible to know/guess all values needed for a proper static config for /etc/network/interfaces. So maybe a message should be added saying that it's necessary to manually edit /etc/network/interfaces?

Just out of curiosity: What were the contents of your config file? And did you get a working static eth0 without changing anything in the template and /etc/network/interfaces?

I'll reopen the issue for now, because I would like to fix this in the future. Will focus on the items in the readme first though :)

**Comment by Napsty** [comment]
My config file looks like that:

```
lxc.tty = 4
lxc.pts = 1024
lxc.rootfs = /var/lib/    lxc/test/rootfs
lxc.cgroup.devices.deny = a
# /dev/null and zero
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
# consoles
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 4:0 rwm
lxc.cgroup.devices.allow = c 4:1 rwm
# /dev/{,u}random
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
# rtc
lxc.cgroup.devices.allow = c 254:0 rwm

# mounts point
lxc.mount.entry=proc /var/lib/    lxc/test/rootfs/proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry=devpts /var/lib/    lxc/test/rootfs/dev/pts devpts defaults 0 0
lxc.mount.entry=sysfs /var/lib/    lxc/test/rootfs/sys sysfs defaults  0 0

# networking

lxc.utsname = test
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = virbr0
lxc.network.ipv4 = 192.168.1.5/24
lxc.network.hwaddr = 00:1E:AF:53:25:97
```

I removed the relevant DHCP part from the template file, created the container with lxc-create and then edited the IP address in the config file. lxc-start seems to then configure the IP of the container as defined in the config file.
