### ISSUE TITLE
Working on lxc-tools

### ISSUE THREAD

**Issue by phenobarbital** [simonvanderveldt/lxc-debian-wheezy-template#5]
Hi!, I'm working on a fully functional version of lxc-templates, I called "lxc-tools"
https://github.com/phenobarbital/lxc-tools

more customizable (wheezy, jessie, sid), various network modes (vlan, macvlan, empty, phys or veth) and backends (lvm, filesystem or btrfs).

go take a look! ...

**Comment by simonvanderveldt** [comment]
Thanks for the heads-up! Are you aware of this project? https://github.com/phbaer/lxc-tools

I want to keep this template as simple as possible so we might have a change of it being added to a Debian stable update.

If by working with LXC you find any kind of issues or usefull addition to the basic lxc-debian-wheezy template please let me know!

I'll close this issue, since it isn't really an issue ;)
